// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionService.Infrastructure.Persistence;

#nullable disable

namespace serviciotransaction.Migrations
{
    [DbContext(typeof(ProyectContext))]
    [Migration("20250203210956_AjusteTiposDeDatos")]
    partial class AjusteTiposDeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionService.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id_Transaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Transaccion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha_Transaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Transaccion");

                    b.Property<decimal>("Id_Cliente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Id_Cliente");

                    b.Property<decimal>("Id_OrigenCli")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Id_OrigenCli");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.HasKey("Id_Transaccion");

                    b.ToTable("Transaccion", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
